// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for BarcodeLookup.
    /// </summary>
    public static partial class BarcodeLookupExtensions
    {
            /// <summary>
            /// Lookup a barcode value and return product data
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// Barcode value
            /// </param>
            public static EanLookupOKResponse EanLookup(this IBarcodeLookup operations, string value)
            {
                return Task.Factory.StartNew(s => ((IBarcodeLookup)s).EanLookupAsync(value), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Lookup a barcode value and return product data
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// Barcode value
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<EanLookupOKResponse> EanLookupAsync(this IBarcodeLookup operations, string value, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.EanLookupWithHttpMessagesAsync(value, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
