// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ConvertTemplate.
    /// </summary>
    public static partial class ConvertTemplateExtensions
    {
            /// <summary>
            /// Apply HTML template
            /// </summary>
            /// Apply operations to fill in an HTML template, generating a final HTML
            /// result
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// Operations to apply to template
            /// </param>
            public static ApplyHtmlTemplateOKResponse ApplyHtmlTemplate(this IConvertTemplate operations, Value value)
            {
                return Task.Factory.StartNew(s => ((IConvertTemplate)s).ApplyHtmlTemplateAsync(value), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Apply HTML template
            /// </summary>
            /// Apply operations to fill in an HTML template, generating a final HTML
            /// result
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// Operations to apply to template
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<ApplyHtmlTemplateOKResponse> ApplyHtmlTemplateAsync(this IConvertTemplate operations, Value value, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApplyHtmlTemplateWithHttpMessagesAsync(value, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
