// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// ConvertTemplate operations.
    /// </summary>
    public partial interface IConvertTemplate
    {
        /// <summary>
        /// Apply HTML template
        /// </summary>
        /// Apply operations to fill in an HTML template, generating a final
        /// HTML result
        /// <param name='value'>
        /// Operations to apply to template
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<ApplyHtmlTemplateOKResponse>> ApplyHtmlTemplateWithHttpMessagesAsync(Value value, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
