// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Email operations.
    /// </summary>
    public partial interface IEmail
    {
        /// <summary>
        /// Validate email adddress for syntactic correctness only
        /// </summary>
        /// Validate whether a given email address is syntactically correct
        /// via a limited local-only check.  Use the address/full API to do a
        /// full validation.
        /// <param name='value'>
        /// Email address to validate, e.g. "support@cloudmersive.com"
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PostOKResponse>> PostWithHttpMessagesAsync(string value, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Partially check whether an email address is valid
        /// </summary>
        /// Validate an email address by identifying whether its parent domain
        /// has email servers defined.  This call is less limited than
        /// syntaxOnly but not as comprehensive as address/full.
        /// <param name='email'>
        /// Email address to validate, e.g. "support@cloudmersive.com"
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<AddressGetServersOKResponse>> AddressGetServersWithHttpMessagesAsync(string email, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
        /// <summary>
        /// Fully validate an email address
        /// </summary>
        /// Performs a full validation of the email address.  Checks for
        /// syntactic correctness, identifies the mail server in question if
        /// any, and then contacts the email server to validate the existence
        /// of the account - without sending any emails.
        /// <param name='email'>
        /// Email address to validate, e.g. "support@cloudmersive.com"
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<FullValidationOKResponse>> FullValidationWithHttpMessagesAsync(string email, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
