// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// ImageOcr operations.
    /// </summary>
    public partial interface IImageOcr
    {
        /// <summary>
        /// Converts an uploaded image in common formats such as JPEG, PNG
        /// into text via Optical Character Recognition.
        /// </summary>
        /// <param name='imageFile'>
        /// Image file to perform OCR on.  Common file formats such as PNG,
        /// JPEG are supported.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PostOKResponse>> PostWithHttpMessagesAsync(System.IO.Stream imageFile, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
