// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// IPAddress operations.
    /// </summary>
    public partial interface IIPAddress
    {
        /// <summary>
        /// Geolocate an IP address
        /// </summary>
        /// Identify an IP address Country, State/Provence, City, Zip/Postal
        /// Code, etc.  Useful for security and UX applications.
        /// <param name='value'>
        /// IP address to geolocate, e.g. "55.55.55.55"
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PostOKResponse>> PostWithHttpMessagesAsync(string value, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
