// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// LanguageDetection operations.
    /// </summary>
    public partial interface ILanguageDetection
    {
        /// <summary>
        /// Detect language of text
        /// </summary>
        /// Automatically determine which language a text string is written
        /// in.  Supports Danish (DAN), German (DEU), English (ENG), French
        /// (FRA), Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD),
        /// Norwegian (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA),
        /// Swedish (SWE), Chinese (ZHO).
        /// <param name='textToDetect'>
        /// Text to detect language of
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<PostOKResponse>> PostWithHttpMessagesAsync(string textToDetect, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
