// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for IPAddress.
    /// </summary>
    public static partial class IPAddressExtensions
    {
            /// <summary>
            /// Geolocate an IP address
            /// </summary>
            /// Identify an IP address Country, State/Provence, City, Zip/Postal Code,
            /// etc.  Useful for security and UX applications.
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// IP address to geolocate, e.g. "55.55.55.55"
            /// </param>
            public static PostOKResponse Post(this IIPAddress operations, string value)
            {
                return Task.Factory.StartNew(s => ((IIPAddress)s).PostAsync(value), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Geolocate an IP address
            /// </summary>
            /// Identify an IP address Country, State/Provence, City, Zip/Postal Code,
            /// etc.  Useful for security and UX applications.
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='value'>
            /// IP address to geolocate, e.g. "55.55.55.55"
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PostOKResponse> PostAsync(this IIPAddress operations, string value, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(value, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
