// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections.Generic;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Resize operations.
    /// </summary>
    public partial interface IResize
    {
        /// <summary>
        /// Resize an image with parameters
        /// </summary>
        /// Resize an image to a maximum width and maximum height, while
        /// preserving the image's original aspect ratio
        /// <param name='maxWidth'>
        /// Maximum width of the output image - final image will be as large
        /// as possible while less than or equial to this width
        /// </param>
        /// <param name='maxHeight'>
        /// Maximum height of the output image - final image will be as large
        /// as possible while less than or equial to this height
        /// </param>
        /// <param name='imageFile'>
        /// Image file to perform the operation on.  Common file formats such
        /// as PNG, JPEG are supported.
        /// </param>
        /// <param name='customHeaders'>
        /// The headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        Task<HttpOperationResponse<object>> PostWithHttpMessagesAsync(int maxWidth, int maxHeight, System.IO.Stream imageFile, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
    }
}
