// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for LanguageDetection.
    /// </summary>
    public static partial class LanguageDetectionExtensions
    {
            /// <summary>
            /// Detect language of text
            /// </summary>
            /// Automatically determine which language a text string is written in.
            /// Supports Danish (DAN), German (DEU), English (ENG), French (FRA),
            /// Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian
            /// (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE),
            /// Chinese (ZHO).
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='textToDetect'>
            /// Text to detect language of
            /// </param>
            public static PostOKResponse Post(this ILanguageDetection operations, string textToDetect)
            {
                return Task.Factory.StartNew(s => ((ILanguageDetection)s).PostAsync(textToDetect), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Detect language of text
            /// </summary>
            /// Automatically determine which language a text string is written in.
            /// Supports Danish (DAN), German (DEU), English (ENG), French (FRA),
            /// Italian (ITA), Japanese (JPN), Korean (KOR), Dutch (NLD), Norwegian
            /// (NOR), Portuguese (POR), Russian (RUS), Spanish (SPA), Swedish (SWE),
            /// Chinese (ZHO).
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='textToDetect'>
            /// Text to detect language of
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PostOKResponse> PostAsync(this ILanguageDetection operations, string textToDetect, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(textToDetect, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
