// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for PosTaggerJson.
    /// </summary>
    public static partial class PosTaggerJsonExtensions
    {
            /// <summary>
            /// Part-of-speech tag a string
            /// </summary>
            /// Part-of-speech (POS) tag a string and return result as JSON
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// Input string
            /// </param>
            public static PostOKResponse Post(this IPosTaggerJson operations, Request request)
            {
                return Task.Factory.StartNew(s => ((IPosTaggerJson)s).PostAsync(request), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Part-of-speech tag a string
            /// </summary>
            /// Part-of-speech (POS) tag a string and return result as JSON
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// Input string
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PostOKResponse> PostAsync(this IPosTaggerJson operations, Request request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
