// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Scan.
    /// </summary>
    public static partial class ScanExtensions
    {
            /// <summary>
            /// Scan a file for viruses
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='inputFile'>
            /// Input file to perform the operation on.
            /// </param>
            public static FileOKResponse File(this IScan operations, System.IO.Stream inputFile)
            {
                return Task.Factory.StartNew(s => ((IScan)s).FileAsync(inputFile), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <summary>
            /// Scan a file for viruses
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='inputFile'>
            /// Input file to perform the operation on.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<FileOKResponse> FileAsync(this IScan operations, System.IO.Stream inputFile, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.FileWithHttpMessagesAsync(inputFile, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
