// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Result of a partial email address validation
    /// </summary>
    public partial class AddressGetServersOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the AddressGetServersOKResponse
        /// class.
        /// </summary>
        public AddressGetServersOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the AddressGetServersOKResponse
        /// class.
        /// </summary>
        public AddressGetServersOKResponse(bool? success = default(bool?), IList<string> servers = default(IList<string>))
        {
            Success = success;
            Servers = servers;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Success")]
        public bool? Success { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Servers")]
        public IList<string> Servers { get; set; }

    }
}
