// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Response from an HTML template application
    /// </summary>
    public partial class ApplyHtmlTemplateOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the ApplyHtmlTemplateOKResponse
        /// class.
        /// </summary>
        public ApplyHtmlTemplateOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the ApplyHtmlTemplateOKResponse
        /// class.
        /// </summary>
        public ApplyHtmlTemplateOKResponse(bool? successful = default(bool?), string finalHtml = default(string))
        {
            Successful = successful;
            FinalHtml = finalHtml;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Successful")]
        public bool? Successful { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FinalHtml")]
        public string FinalHtml { get; set; }

    }
}
