// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Spell check result
    /// </summary>
    public partial class CheckJsonOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the CheckJsonOKResponse class.
        /// </summary>
        public CheckJsonOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the CheckJsonOKResponse class.
        /// </summary>
        public CheckJsonOKResponse(bool? correct = default(bool?))
        {
            Correct = correct;
        }

        /// <summary>
        /// True if spellected correctly, false otherwise
        /// </summary>
        [JsonProperty(PropertyName = "Correct")]
        public bool? Correct { get; set; }

    }
}
