// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Spelling correction check result
    /// </summary>
    public partial class CorrectJsonOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the CorrectJsonOKResponse class.
        /// </summary>
        public CorrectJsonOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the CorrectJsonOKResponse class.
        /// </summary>
        public CorrectJsonOKResponse(bool? correct = default(bool?), IList<string> suggestions = default(IList<string>))
        {
            Correct = correct;
            Suggestions = suggestions;
        }

        /// <summary>
        /// True if the word is spelled correctly, false otherwise
        /// </summary>
        [JsonProperty(PropertyName = "Correct")]
        public bool? Correct { get; set; }

        /// <summary>
        /// Suggested spelling corrections
        /// </summary>
        [JsonProperty(PropertyName = "Suggestions")]
        public IList<string> Suggestions { get; set; }

    }
}
