// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The best Machine Learning outcome
    /// </summary>
    public partial class DescribeOKResponseBestOutcome
    {
        /// <summary>
        /// Initializes a new instance of the DescribeOKResponseBestOutcome
        /// class.
        /// </summary>
        public DescribeOKResponseBestOutcome() { }

        /// <summary>
        /// Initializes a new instance of the DescribeOKResponseBestOutcome
        /// class.
        /// </summary>
        public DescribeOKResponseBestOutcome(double? confidenceScore = default(double?), string description = default(string))
        {
            ConfidenceScore = confidenceScore;
            Description = description;
        }

        /// <summary>
        /// Scores closer to 1 are better than scores closer to 0
        /// </summary>
        [JsonProperty(PropertyName = "ConfidenceScore")]
        public double? ConfidenceScore { get; set; }

        /// <summary>
        /// English language description of the image
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
