// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EanLookupOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the EanLookupOKResponse class.
        /// </summary>
        public EanLookupOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the EanLookupOKResponse class.
        /// </summary>
        public EanLookupOKResponse(bool? successful = default(bool?), IList<EanLookupOKResponseMatchesItem> matches = default(IList<EanLookupOKResponseMatchesItem>))
        {
            Successful = successful;
            Matches = matches;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Successful")]
        public bool? Successful { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Matches")]
        public IList<EanLookupOKResponseMatchesItem> Matches { get; set; }

    }
}
