// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Result of running a virus scan
    /// </summary>
    public partial class FileOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the FileOKResponse class.
        /// </summary>
        public FileOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the FileOKResponse class.
        /// </summary>
        public FileOKResponse(bool? cleanResult = default(bool?), IList<FileOKResponseFoundVirusesItem> foundViruses = default(IList<FileOKResponseFoundVirusesItem>))
        {
            CleanResult = cleanResult;
            FoundViruses = foundViruses;
        }

        /// <summary>
        /// True if the scan contained no viruses, false otherwise
        /// </summary>
        [JsonProperty(PropertyName = "CleanResult")]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Array of viruses found, if any
        /// </summary>
        [JsonProperty(PropertyName = "FoundViruses")]
        public IList<FileOKResponseFoundVirusesItem> FoundViruses { get; set; }

    }
}
