// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Full email addresss validation result
    /// </summary>
    public partial class FullValidationOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the FullValidationOKResponse class.
        /// </summary>
        public FullValidationOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the FullValidationOKResponse class.
        /// </summary>
        public FullValidationOKResponse(bool? validAddress = default(bool?), string mailServerUsedForValidation = default(string))
        {
            ValidAddress = validAddress;
            MailServerUsedForValidation = mailServerUsedForValidation;
        }

        /// <summary>
        /// True if the email address is valid, false otherwise
        /// </summary>
        [JsonProperty(PropertyName = "ValidAddress")]
        public bool? ValidAddress { get; set; }

        /// <summary>
        /// Email server connected to for verification
        /// </summary>
        [JsonProperty(PropertyName = "MailServerUsedForValidation")]
        public string MailServerUsedForValidation { get; set; }

    }
}
