// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Details of the screenshot request
    /// </summary>
    public partial class Input
    {
        /// <summary>
        /// Initializes a new instance of the Input class.
        /// </summary>
        public Input() { }

        /// <summary>
        /// Initializes a new instance of the Input class.
        /// </summary>
        public Input(string url = default(string), int? extraLoadingWait = default(int?))
        {
            Url = url;
            ExtraLoadingWait = extraLoadingWait;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExtraLoadingWait")]
        public int? ExtraLoadingWait { get; set; }

    }
}
