// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Results of locating faces in an image
    /// </summary>
    public partial class LocateOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the LocateOKResponse class.
        /// </summary>
        public LocateOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the LocateOKResponse class.
        /// </summary>
        public LocateOKResponse(bool? successful = default(bool?), IList<LocateOKResponseFacesItem> faces = default(IList<LocateOKResponseFacesItem>), int? faceCount = default(int?))
        {
            Successful = successful;
            Faces = faces;
            FaceCount = faceCount;
        }

        /// <summary>
        /// True if the operation was successful, false otherwise
        /// </summary>
        [JsonProperty(PropertyName = "Successful")]
        public bool? Successful { get; set; }

        /// <summary>
        /// Array of faces found in the image
        /// </summary>
        [JsonProperty(PropertyName = "Faces")]
        public IList<LocateOKResponseFacesItem> Faces { get; set; }

        /// <summary>
        /// Number of faces found in the image
        /// </summary>
        [JsonProperty(PropertyName = "FaceCount")]
        public int? FaceCount { get; set; }

    }
}
