// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Result of a WHOIS operation
    /// </summary>
    public partial class PostOKResponse
    {
        /// <summary>
        /// Initializes a new instance of the PostOKResponse class.
        /// </summary>
        public PostOKResponse() { }

        /// <summary>
        /// Initializes a new instance of the PostOKResponse class.
        /// </summary>
        public PostOKResponse(bool? validDomain = default(bool?), string whoisServer = default(string), string rawTextRecord = default(string), DateTime? createdDt = default(DateTime?))
        {
            ValidDomain = validDomain;
            WhoisServer = whoisServer;
            RawTextRecord = rawTextRecord;
            CreatedDt = createdDt;
        }

        /// <summary>
        /// True if the domain is valid, false if it is not
        /// </summary>
        [JsonProperty(PropertyName = "ValidDomain")]
        public bool? ValidDomain { get; set; }

        /// <summary>
        /// Server used to lookup WHOIS information (may change based on
        /// lookup).
        /// </summary>
        [JsonProperty(PropertyName = "WhoisServer")]
        public string WhoisServer { get; set; }

        /// <summary>
        /// WHOIS raw text record
        /// </summary>
        [JsonProperty(PropertyName = "RawTextRecord")]
        public string RawTextRecord { get; set; }

        /// <summary>
        /// Creation date for the record
        /// </summary>
        [JsonProperty(PropertyName = "CreatedDt")]
        public DateTime? CreatedDt { get; set; }

    }
}
