// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Part of speech tagging request
    /// </summary>
    public partial class Request
    {
        /// <summary>
        /// Initializes a new instance of the Request class.
        /// </summary>
        public Request() { }

        /// <summary>
        /// Initializes a new instance of the Request class.
        /// </summary>
        public Request(string inputText = default(string))
        {
            InputText = inputText;
        }

        /// <summary>
        /// Input text string
        /// </summary>
        [JsonProperty(PropertyName = "InputText")]
        public string InputText { get; set; }

    }
}
