// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Cloudmersive.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// HTML template application request
    /// </summary>
    public partial class Value
    {
        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value() { }

        /// <summary>
        /// Initializes a new instance of the Value class.
        /// </summary>
        public Value(string htmlTemplate = default(string), string htmlTemplateUrl = default(string), IList<ValueOperationsItem> operations = default(IList<ValueOperationsItem>))
        {
            HtmlTemplate = htmlTemplate;
            HtmlTemplateUrl = htmlTemplateUrl;
            Operations = operations;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HtmlTemplate")]
        public string HtmlTemplate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "HtmlTemplateUrl")]
        public string HtmlTemplateUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Operations")]
        public IList<ValueOperationsItem> Operations { get; set; }

    }
}
